# Generated by Django 5.2.8 on 2025-12-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='photos',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
